export const ROLES = [
  "Physician - Family Medicine / General Practice",
  "Physician - Internal Medicine",
  "Surgeon",
  "Orthopedic Surgeon",
  "Obstetrician / Gynecologist",
  "Pediatrician",
  "Psychiatrist",
  "Cardiologist",
  "Anesthesiologist",
  "Emergency Medicine Physician",
  "Radiologist",
  "Dermatologist",
  "Neurologist",
  "Oncologist",
  "Medical Student",
  "Registered Nurse",
  "Nurse Practitioner",
  "Nursing Student",
  "Midwife",
  "Physician Assistant",
  "Clinical Pharmacist",
  "Hospital Pharmacist",
  "Community Pharmacist",
  "Pharmacy Resident",
  "Pharmacy Student",
  "Dentist",
  "Physical Therapist",
  "Occupational Therapist",
  "Speech-Language Pathologist",
  "Respiratory Therapist",
  "Dietitian / Nutritionist",
  "Psychologist",
  "Medical Laboratory Scientist",
  "Radiologic Technologist",
  "Paramedic / EMT",
  "Other",
] as const;
